name = "Couette"
meshfile = "mesh.h5"

[timestep]
tend = 0.3
dt = 5e-5

[output]
sample_fraction = 0.95

[species.argon]
T_ref = 273.0
d_ref = 4.05e-10
mass = 6.63e-26
omega = 0.27

[dsmc]
collision_operator = "bgk"
mpf = 1e11

[[boundary]]
identifier = "BC_SYM"
type = "symmetric"

[[boundary]]
identifier = "BC_XPLUS"
type = "diffuse"
accommodation = 1.0
temperature = 280.0
velocity = [0.0, 100.0, 0.0]

[[boundary]]
identifier = "BC_XMINUS"
type = "diffuse"
accommodation = 1.0
temperature = 280.0
velocity = [0.0, -100.0, 0.0]

[[initialization]]
species = "argon"
density = 1.3e18
temperature = 280.0
